var Msg = {
"fix_html" : "Edit HTML",
"msg_1" : "Able to modify HTML code.",
"msg_2" : "Unable  Restore",
"set_order" : "Change Order",
"msg_3" : "Move by Press Button",
"widen" : "Widen",
"narrow" : "Narrow",
"set_type" : "Set Type",
"msg_4" : "Set none width Type",
"add_column" : "Add Column",
"msg_5" : "Add one blank Space",
"add_grid" : "Add a Grid",
"msg_6" : "Add a Row",
"alignment" : "Alignment",
"justify" : "Justify",
"indent" : "Indent",
"outdent" : "Outdent",
"setting" : "Setting",
"title" : "Heading(H)",
"paragraph" : "Paragraph(P)",
"box" : "Division(DIV)",
"text" : "Span",
"blockquote" : "Blockquote",
"fix_size" : "Change Size",
"exsertion" : "External Insertion",
"insertion" : "Internal Insertion",
"image" : "Image",
"unorder_list" : "Unordered List",
"order_list" : "Ordered List",
"table" : "Table",
"special_characters" : "Special Characters",
"icon" : "Icon",
"button" : "Button",
"video" : "Video",
"map" : "Map",
"copy" : "Copy",
"paste" : "Paste",
"msg_25" : "Click",
"delete" : "Delete",
"upload" : "Upload",
"msg_7" : "Optimal Size",
"msg_8" : "Double-Click to apply after setting the size.",
"set_link" : "Change Link",
"explan" : "Explanation",
"msg_9" : "Enter Link Destcription",
"url" : "URL",
"msg_10" : "Enter Link URL",
"new_window" : "New Window",
"msg_11" : "Open in a new window.",
"msg_12" : "Set Basic Mode",
"msg_13" : "Set Background Mode",
"basic_mode" : "Basic Mode",
"background_mode" : "Bacground Mode",
"set_location" : "Set Location",
"optimal" : "Optimal",
"size_up" : "Size Up",
"size_down" : "Size Down",
"apply" : "Apply ",
"msg_14" : "Unable Size Down",
"search" : "Search",
"etc" : "Etc",
"or" : "Or",
"set_icon" : "Set Icon",
"msg_15" : "Double click to change the icon.",
"size" : "Size",
"auto" : "Auto",
"kind" : "Type",
"classifiction" : "Classification",
"set_color" : "Change Color",
"symbols" : "General Symbols",
"numbers_units" : "Numbers and Units",
"bracket" : "Bracket",
"circle" : "Circle ",
"korean" : "Korean",
"greek_latin" : "Greek, Latin",
"japanese" : "Japanese",
"set_shape" : "Set Shape",
"set_button" : "Set Button",
"msg_16" : "You can make more variety with [Settings].",
"insert" : "Insert",
"delete" : "Delete",
"msg_17" : "The icon does not exist.",
"set_style" : "Set Style",
"msg_18" : "Unable to set due to arrange in single line",
"set_video" : "Set Video",
"enter_url" : "Enter URL(link address, file path)",
"enter_code" : "Enter Source Code",
"fix_map" : "Change Map",
"set_map" : "Edit Map",
"find_coor" : "Find Coordinates",
"co_name" : "Company Name",
"addr" : "Address",
"x_coor" : "X Coordinate",
"y_coor" : "Y Coordinate",
"zoom" : "Zoom",
"msg_19" : "Optimal:16~17",
"msg_20" : "Show Street Map",
"terrain" : "Terrain",
"satellite" : "Satellite",
"msg_21" : "View Satellite Images",
"msg_22" : "View full screen",
"find" : "Find",
"zoom_in" : "Zoom In",
"zoom_out" : "Zoom Out",
"table_setting" : "Edit Table",
"design" : "Design",
"head_color" : "Head Color",
"caption" : "Caption",
"msg_23" : "Table caption must be entered.",
"summary" : "Summary",
"msg_24" : "Ex) Table consist with 3 columns, 1st column : Size of Real Eastate, 2nd column: Sales Price per Size, 3rd Column: Rental Price per Size",
"table_btn_1" : "Merge Cells",
"table_btn_2" : "Cell Vertical Division",
"table_btn_3" : "Cell Horizontal Division",
"table_btn_4" : "Cell Width Equal",
"table_btn_5" : "Change Left and Right Order",
"table_btn_6" : "Change Top and Bottom Order",
"table_btn_7" : "Add Column on Right",
"table_btn_8" : "Add Column on Left",
"table_btn_9" : "Add Column on Bottom",
"table_btn_10" : "Add Column on Upper",
"table_btn_11" : "Delete Line",
"table_btn_12" : "Delete Cell",
"table_btn_13" : "Delete Table",
"content" : "Content",
"msg_26" : "Not Apply on Main(P)Tag",
"object_setting" : "Object Settings",
"general_setting" : "General Settings",
"class" : "Class",
"style" : "Style",
"shape" : "Shape",
"pattern" : "Pattern",
"color" : "Color",
"effect" : "Effect",
"text" : "Text",
"custom" : "User Setting",
"line_height" : "Line Height",
"word_spacing" : "Word Spacing",
"letter_spacing" : "Letter Spacing",
"border" : "Border",
"width" : "Width",
"all" : "All",
"solid" : "Solid",
"dotted" : "Dotted",
"dashed" : "Dashed",
"double" : "Double",
"groove" : "Groove",
"ridge" : "Ridge",
"inset" : "Inset",
"outset" : "Outset",
"radius" : "Border Radius",
"text_shadow" : "Text Shadow",
"top_left" : "Top Left",
"top_right" : "Top Right",
"bottom_left" : "Bottom Left",
"bottom_right" : "Bottom Right",
"bg_color" : "Background Color",
"bg" : "Background",
"property_remove" : "Property Remove",
"padding" : "Padding",
"location" : "Location",
"margin" : "Margin",
"text_align" : "Text Align",
"none" : "None",
"center" : "Center",
"vertical_align" : "Vertical Align",
"bold" : "Bold",
"italic" : "Italic",
"underline" : "Underline",
"line_through" : "Line Through",
"font_family" : "Font Family",
"sup" : "Superscript",
"sub" : "Subscript",
"link" : "Link",
"top" : "Top",
"right" : "Right",
"bottom" : "Bottom",
"left" : "Left",
"center" : "Center",
"msg_27" : "Unable to Change Type for Current Item",
"msg_28" : "Done to change [%1]",
"msg_29" : "Only upload image file Available extension file [jpg,jpeg,gif,png,bmp,webp] ",
"msg_30" : "[%1] is aleady uploaded image!",
"msg_31" : "[%1] files can be uploaded",
"msg_32" : "Unable to upload exceeding [%3] size file.",
"msg_33" : "Unable to upoad due to [%1] file extentsion",
"set_list" : "Edit List",
"msg_34" : "Select the field to copy.",
"msg_35" : "Select the field to delete.",
"msg_36" : "Enter Contents.",
"msg_37" : "If you leave this page, the contents will not be saved.",
"msg_38" : "Should be selected more than two cells, Please drag and select. ",
"msg_39" : "Only each of Header[thead], content[tbody], footer[tfoot] can be Merged",
"msg_40" : "Invalid drag range. Drag in a square shape.",
"msg_41" : "Unable to change due to  <thead>",
"msg_42" : "Available only one line",
"msg_43" : "Unable to chace due to <tfoot>",
"msg_44" : "Select more than one cell for vertical divide",
"msg_45" : "Select more than one cell for horizontal divide",
"msg_46" : "Unable to copy for [%1] tag",
"msg_47" : "Able to Group Copy to Select [OK] for Group Copy Select [NO] for individual copy.",
"msg_48" : "Wrong location for exteranl insert. ",
"msg_49" : "Example Paragraph, Easy to modfy using Editor and Text Converter. ",
"msg_50" : "Able to Delete [Group] to Select [OK] for Group Delete Select [NO] for Individual Delete.",
"msg_51" : "Unable to delete anymore",
"msg_52" : "Unable sequence elements(tag) to reorder",
"msg_53" : "You can change the order to [Group]. If you want to change the order [group], please select OK. If you select NO, Only the currently selected [Object] will change the order",
"remove_font_property" : "Remove Font Property",
"delete_link" : "Delete Link",
"top_copy" : "Top Copy",
"msg_54" : "Drags main texts up to wish to insert. ",
"msg_55" : "Unable to exceed total [%1] cells",
"msg_56" : "Unable to delete anymore",
"msg_57" : "Unable to extend anymore",
"msg_58" : "Unable to reduce anymore",
"msg_59" : "Input Description of the image",
"msg_60" : "Input Address to link.",
"msg_61" : "If checked, the link will open in a new window.",
"msg_62" : "Unable to reduce anymore",
"print_place" : "Printing Location ",
"print_address" : "Printing Address",
"msg_63" : "Move the marker to set the correct position.",	
"merge" : "Merge",	
"divide" : "Divide",	
"convert" : "Convert",	
"fix" : "Fix",	
"add" : "Add",	
"remove" : "Remove",	
"spacing" : "Spacing",	
"text_color" : "Text Color",	
"font_size" : "Font Size",	
"font_class" : "Font Class",	
"msg_64" : "Select the location to copy.",	
"msg_65" : "Select the location to insert.",
"msg_66" : "Unable to delete tag [%1].",
"strong" : "Emphasis",
"save" : "SAVE",
"new_content" : "New",
"msg_67" : "Delete this document?",
"msg_68" : "Do you want to delete? Unable to restore.",
"msg_69" : "Unable to copy with the lock function.",
"inherit" : "Inherit",
"msg_70" : "Not available in PC mode!",
"msg_71" : "Proceeding",
"column_set" : "Column alignment", 
"msg_72" : "Mobile only",
"complete" : "Complete", 

"set_tab" : "Tab box Settings",
"slide" : "SLIDE",

"set_program" : "Ajax Program Settings",
"id" : "ID",
"program_name" : "Program Name",
"program_type" : "Program Type",
"db" : "Database",

"tag_setting" : "Tag settings",
"tag" : "Tag",
"property" : "Property",

"HEADING" : "HEADING",
"P" : "P",
"DIV" : "DIV",
"A" : "LINK",
"SPAN" : "SPAN",
"BLOCKQUOTE" : "BLOCKQUOTE",

"msg_73" : "It has been copied.",
"group" : "Group",
"no" : "Number",
"mouseover" : "Mouse Over",
"preview" : "Preview",
"view" : "View",
"hide" : "Hide",
"msg_74" : "Enter the text to be displayed.",

// 2023-05-04 추가
"button_setting" : "Button Settings",
"use" : "Use",
"msg_75" : "Cannot paste the object.",
"msg_76" : "No object copied.",
"mode" : "Mode",
"msg_77" : "Only in the [tbody] tag!",
"msg_78" : "[%1]\nCannot overlap!",
"map_setting" : "Map settings",
"msg_79" : "Please enter the address to search", // 지도
"msg_80" : "This feature is only available in the PRO version. \nIf you upgrade, you can use more features.",
"msg_81" : "UPGRADE NOW",
"grid_setting" : "Grid settings",
"msg_82" : "Only available on PC.",
};
