var Msg = {
"fix_html" : "Editar HTML",
"msg_1" : "Capaz de modificar el código HTML.",
"msg_2" : "Restauración no recuperable",
"set_order" : "Cambia el orden",
"msg_3" : "Mover por el botón de prensa",
"widen" : "Ensanchar",
"narrow" : "Estrecho",
"set_type" : "Cambiar tipo",
"msg_4" : "Establecer (ninguno) ancho Tipo",
"add_column" : "Agregar nueva columna",
"msg_5" : "Agrega un espacio en blanco",
"add_grid" : "Agregar una cuadrícula",
"msg_6" : "Agregar una fila",
"alignment" : "Alineación",
"justify" : "Justificar",
"indent" : "Aplicar sangría",
"outdent" : "Anular sangría",
"setting" : "Valor",
"title" : "Heading",
"paragraph" : "Paragraph",
"box" : "Division",
"text" : "Span",
"blockquote" : "Blockquote",
"fix_size" : "Cambiar tamaño",
"exsertion" : "Inserción Externa",
"insertion" : "Inserción Interna",
"image" : "Imagen",
"unorder_list" : "Lista desordenada",
"order_list" : "Lista ordenada",
"table" : "Tabla",
"special_characters" : "Caracteres especiales",
"icon" : "Icono",
"button" : "Botón",
"video" : "Vídeo",
"map" : "Mapa",
"copy" : "Copia",
"paste" : "Pegar",
"msg_25" : "Haz clic",
"delete" : "Borrar",
"upload" : "Subir",
"msg_7" : "Tamaño óptimo",
"msg_8" : "Doble clic para aplicar después de configurar el tamaño.",
"set_link" : "Cambiar enlace",
"explan" : "Explicación",
"msg_9" : "Ingrese la Destinación del Enlace",
"url" : "URL",
"msg_10" : "Actualizar la dirección del sitio (URL)",
"new_window" : "Nueva ventana",
"msg_11" : "Abrir en una nueva ventana.",
"msg_12" : "Establecer el modo básico",
"msg_13" : "Establecer el modo de fondo",
"basic_mode" : "Modo básico",
"background_mode" : "Modo Bacground",
"set_location" : "Cambiar ubicación",
"optimal" : "Óptimo",
"size_up" : "Formarse un juicio de",
"size_down" : "Reducir el tamaño",
"apply" : "Aplicar",
"msg_14" : "No se puede bajar el tamaño",
"search" : "Buscar",
"etc" : "Etc",
"or" : "O",
"set_icon" : "Establecer icono",
"msg_15" : "Haga doble clic para cambiar el ícono.",
"size" : "Tamaño",
"auto" : "Auto",
"kind" : "Tipo",
"classifiction" : "Clasificación",
"set_color" : "Cambiar el color",
"symbols" : "Símbolos generales",
"numbers_units" : "Números y unidades",
"bracket" : "Corchete",
"circle" : "Círculo",
"korean" : "Coreano",
"greek_latin" : "Griego, latín",
"japanese" : "Japonés",
"set_shape" : "Establecer forma",
"set_button" : "Botón de ajuste",
"msg_16" : "Puede hacer más variedad con [Configuración].",
"insert" : "Insertar",
"delete" : "Borrar",
"msg_17" : "El icono no existe.",
"set_style" : "Establecer estilo",
"msg_18" : "No se puede establecer debido a organizar en una sola línea",
"set_video" : "Establecer video",
"enter_url" : "Ingrese la URL (dirección del enlace, ruta del archivo)",
"enter_code" : "Ingrese el código fuente",
"fix_map" : "Cambiar mapa",
"set_map" : "Editar mapa",
"find_coor" : "Encontrar coordenadas",
"co_name" : "Nombre de la compañía",
"addr" : "Dirección",
"x_coor" : "Coordenada X",
"y_coor" : "Coordenada Y",
"zoom" : "Enfocar",
"msg_19" : "Óptimo: 16 ~ 17",
"msg_20" : "Mostrar el mapa de la calle",
"terrain" : "Terreno",
"satellite" : "Satélite",
"msg_21" : "Ver imágenes de satélite",
"msg_22" : "Ver en pantalla completa",
"find" : "Buscar",
"zoom_in" : "Acercarse",
"zoom_out" : "Disminuir el zoom",
"table_setting" : "Editar tabla",
"design" : "Diseño",
"head_color" : "Color de cabeza",
"caption" : "Subtítulo",
"msg_23" : "La leyenda de la tabla debe ingresarse.",
"summary" : "Resumen",
"msg_24" : "Ej. La tabla consiste en 3 columnas, 1ra columna: Tamaño del real Eastate, 2da columna: Precio de venta por tamaño, 3ra columna: Precio de alquiler por tamaño",
"table_btn_1" : "Combinar celdas",
"table_btn_2" : "División vertical celular",
"table_btn_3" : "División horizontal celular",
"table_btn_4" : "Ancho de celda igual",
"table_btn_5" : "Cambiar orden izquierda y derecha",
"table_btn_6" : "Cambiar el orden superior e inferior",
"table_btn_7" : "Agregar columna a la derecha",
"table_btn_8" : "Agregar columna a la izquierda",
"table_btn_9" : "Agregar columna en la parte inferior",
"table_btn_10" : "Agregar columna en la parte superior",
"table_btn_11" : "Eliminar línea",
"table_btn_12" : "Eliminar celda",
"table_btn_13" : "Eliminar tabla",
"content" : "Contenido",
"msg_26" : "No se aplica en la etiqueta principal (P)",
"object_setting" : "Configuración del objeto",
"general_setting" : "Configuración general",
"class" : "Clase",
"style" : "Estilo",
"shape" : "Forma",
"pattern" : "Patrón",
"color" : "Color",
"effect" : "Efecto",
"text" : "Texto",
"custom" : "Personalizado",
"line_height" : "Altura de linea",
"word_spacing" : "Separación entre entradas de lápiz",
"letter_spacing" : "Espaciado de letras",
"border" : "Borde",
"width" : "Ancho",
"all" : "Todo",
"solid" : "Sólido",
"dotted" : "Punteado",
"dashed" : "Linea discontinua",
"double" : "Doble",
"groove" : "Surco",
"ridge" : "Rugoso",
"inset" : "Recuadro",
"outset" : "Comienzo",
"radius" : "Radio del borde",
"text_shadow" : "Sombra de texto",
"top_left" : "Arriba izquierda",
"top_right" : "Arriba derecha",
"bottom_left" : "Abajo izquierda",
"bottom_right" : "Abajo derecha",
"bg_color" : "Color de fondo",
"bg" : "Fondo",
"property_remove" : "Reiniciar",
"padding" : "Relleno",
"location" : "Ubicación",
"margin" : "Margen",
"text_align" : "Alineación del texto",
"none" : "Ninguno",
"center" : "Centro",
"vertical_align" : "Alineación vertical",
"bold" : "Negrita",
"italic" : "Cursiva",
"underline" : "Subrayado",
"line_through" : "Tachado",
"font_family" : "Fuente",
"sup" : "Sobrescrito",
"sub" : "Subíndice",
"link" : "Enlace",
"top" : "Arriba",
"right" : "Derecha",
"bottom" : "Abajo",
"left" : "Izquierda",
"center" : "Centro",
"msg_27" : "No se puede cambiar el tipo para el elemento actual",
"msg_28" : "Hecho para cambiar [%1]",
"msg_29" : "Cargar solo archivo de imagen Archivo de extensión disponible [jpg, jpeg, gif, png, bmp, webp]",
"msg_30" : "[%1] ya está cargada la imagen!",
"msg_31" : "[%1] archivos pueden cargarse",
"msg_32" : "No se puede cargar más del archivo de tamaño [% 3].",
"msg_33" : "No se puede abrir debido a la extensión del archivo [%1]",
"set_list" : "Lista de edición",
"msg_34" : "Seleccione el campo para copiar.",
"msg_35" : "Seleccione el campo para eliminar.",
"msg_36" : "Ingrese el contenido.",
"msg_37" : "Si abandona esta página, los contenidos no se guardarán.",
"msg_38" : "Se deben seleccionar más de dos celdas, arrastre y seleccione.",
"msg_39" : "Solo se pueden fusionar cada uno de Header [thead], content [tbody], footer [tfoot]",
"msg_40" : "Rango de arrastre no válido Arrastre en forma cuadrada.",
"msg_41" : "No se puede cambiar debido a <thead>",
"msg_42" : "Disponible solo una linea",
"msg_43" : "No se puede chace debido a <tfoot>",
"msg_44" : "Seleccione más de una celda para división vertical",
"msg_45" : "Seleccione más de una celda para división horizontal",
"msg_46" : "No se puede copiar la etiqueta [%1]",
"msg_47" : "Capaz de Copiar Grupo para Seleccionar [OK] para Copiar Grupo Seleccione [NO] para copia individual.",
"msg_48" : "Ubicación incorrecta para inserción exteranl.",
"msg_49" : "Párrafo de ejemplo, fácil de modificar usando el editor y el convertidor de texto.",
"msg_50" : "Capaz de Eliminar [Grupo] para Seleccionar [OK] para Grupo Eliminar Seleccione [NO] para Borrar Individual.",
"msg_51" : "Ya no se puede eliminar",
"msg_52" : "Elementos de secuencia no permitidos (etiqueta) para reordenar",
"msg_53" : "Puede cambiar el orden a [Grupo]. Si quiere cambiar el orden [grupo], seleccione OK. Si selecciona NO, solo el [Objeto] seleccionado actualmente cambiará la orden",
"remove_font_property" : "Eliminar propiedad de fuente",
"delete_link" : "Eliminar enlace",
"top_copy" : "Copia superior",
"msg_54" : "Arrastra los textos principales hasta desear insertarlos.",
"msg_55" : "No se pueden superar las celdas totales [%1]",
"msg_56" : "Ya no se puede eliminar",
"msg_57" : "No se puede extender más",
"msg_58" : "No se puede reducir más",
"msg_59" : "Entrada Descripción de la imagen",
"msg_60" : "Dirección de entrada para vincular.",
"msg_61" : "Si está marcado, el enlace se abrirá en una nueva ventana.",
"msg_62" : "No se puede reducir más",
"print_place" : "Ubicación de impresión",
"print_address" : "Imprimir dirección",
"msg_63" : "Mueva el marcador para establecer la posición correcta.",
"merge" : "Unir",
"divide" : "Dividir",
"convert" : "Convertir",
"fix" : "Fijar",
"add" : "Añadir",
"remove" : "retirar",
"spacing" : "Espaciado",
"text_color" : "Color de texto",
"font_size" : "Tamaño de fuente",
"font_class" : "Clase de fuente",
"msg_64" : "Seleccione la ubicación para copiar.",
"msg_65" : "Seleccione la ubicación para insertar.",
"msg_66" : "No se puede eliminar la etiqueta [%1].",
"strong" : "Énfasis",
"save" : "Salvar",
"new_content" : "Nuevo",
"msg_67" : "¿Está seguro de que desea eliminar este documento?",
"msg_68" : "¿Quieres borrar? No se puede restaurar.",
"msg_69" : "No se puede copiar con la función de bloqueo.",
"inherit" : "Hereda",
"msg_70" : "No disponible en modo PC!",
"msg_71" : "En proceso",
"column_set" : "Alineación columna", 
"msg_72" : "Solo móvil",
"complete" : "Completado", 

"set_tab" : "Configuración del cuadro de pestañas",
"slide" : "SLIDE",

"set_program" : "Configuración del programa Ajax",
"id" : "ID",
"program_name" : "Program Name",
"program_type" : "Program Type",
"db" : "Database",

"tag_setting" : "Tag settings",
"tag" : "Tag",
"property" : "Property",

"HEADING" : "HEADING",
"P" : "P",
"DIV" : "DIV",
"A" : "LINK",
"SPAN" : "SPAN",
"BLOCKQUOTE" : "BLOCKQUOTE",

"msg_73" : "Copied",
"group" : "Group",
"no" : "Number",
"mouseover" : "Mouse Over",
"preview" : "Preview",
"view" : "View",
"hide" : "Hide",
"msg_74" : "Introduzca el texto que se mostrará.",

// 2023-05-04 추가
"button_setting" : "Configuración del botón",
"use" : "Usar",
"msg_75" : "No se puede pegar el objeto.",
"msg_76" : "No hay objetos copiados.",
"mode" : "Modo",
"msg_77" : "¡Solo es posible en la etiqueta [tbody]!",
"msg_78" : "No se puede anidar [%1].",
"map_setting" : "Configuración del mapa",
"msg_79" : "Ingrese la dirección para buscar", // 지도
"msg_80" : "Esta función solo está disponible en la versión PRO. \nActualícese para usar más funciones.",
"msg_81" : "Actualizar ahora",
"grid_setting" : "Configuración de la cuadrícula",
"msg_82" : "Solo es posible en PC.",
};
