var Msg = {
"fix_html" : "Modifier le code HTML",
"msg_1" : "Capable de modifier le code HTML.",
"msg_2" : "Impossible de restaurer",
"set_order" : "Change l'ordre",
"msg_3" : "Bouton de déplacement par presse",
"widen" : "Élargir",
"narrow" : "Étroit",
"set_type" : "Modifier le type",
"msg_4" : "Définir (aucune) largeur Type",
"add_column" : "Ajouter une nouvelle colonne",
"msg_5" : "Ajouter un espace vide",
"add_grid" : "Ajouter une grille",
"msg_6" : "Ajouter une ligne",
"alignment" : "Alignement",
"justify" : "Justifier",
"indent" : "Retrait",
"outdent" : "Retrait négatif",
"setting" : "paramètre",
"title" : "Heading(H)",
"paragraph" : "Paragraph(P)",
"box" : "Division(DIV)",
"text" : "Span",
"blockquote" : "Blockquote",
"fix_size" : "Modifier la taille",
"exsertion" : "Insertion externe",
"insertion" : "Insertion Interne",
"image" : "Image",
"unorder_list" : "Liste non ordonnée",
"order_list" : "Liste ordonnée",
"table" : "Table",
"special_characters" : "Caractères spéciaux",
"icon" : "Icône",
"button" : "Bouton",
"video" : "Vidéo",
"map" : "Carte",
"copy" : "Copie",
"paste" : "Colar",
"msg_25" : "Clic",
"delete" : "Supprimer",
"upload" : "télécharger",
"msg_7" : "Taille optimale",
"msg_8" : "Double-cliquez pour appliquer après avoir défini la taille.",
"set_link" : "Changer le lien",
"explan" : "Explication",
"msg_9" : "Entrer le lien Destcription",
"url" : "URL",
"msg_10" : "Mettre à jour l’adresse du site (URL)",
"new_window" : "Nouvelle fenêtre",
"msg_11" : "Ouvrir dans une nouvelle fenêtre.",
"msg_12" : "Définir le mode de base",
"msg_13" : "Définir le mode d'arrière-plan",
"basic_mode" : "Mode simple",
"background_mode" : "Mode de fond",
"set_location" : "Den Ort wechseln.",
"optimal" : "Optimal",
"size_up" : "Taille jusqu'à",
"size_down" : "Taille vers le bas",
"apply" : "Appliquer",
"msg_14" : "Taille impossible vers le bas",
"search" : "Chercher",
"etc" : "Etc",
"or" : "Ou",
"set_icon" : "Set Icon",
"msg_15" : "Double-cliquez pour changer l'icône.",
"size" : "Taille",
"auto" : "Auto",
"kind" : "Type",
"classifiction" : "Classification",
"set_color" : "Changer de couleur",
"symbols" : "Symboles généraux",
"numbers_units" : "Nombres et unités",
"bracket" : "Crochet",
"circle" : "Cercle",
"korean" : "Coréen",
"greek_latin" : "Grec, latin",
"japanese" : "Japonais",
"set_shape" : "Modifier la forme",
"set_button" : "Bouton de réglage",
"msg_16" : "Vous pouvez faire plus de variété avec [Paramètres].",
"insert" : "Insertion",
"delete" : "Supprimer",
"msg_17" : "L'icône n'existe pas.",
"set_style" : "Définir le style",
"msg_18" : "Impossible de définir en raison d'arranger en une seule ligne",
"set_video" : "Définir la vidéo",
"enter_url" : "Entrez l'URL (adresse du lien, chemin du fichier)",
"enter_code" : "Entrez le code source",
"fix_map" : "Changer de carte",
"set_map" : "Modifier la carte",
"find_coor" : "Trouver des coordonnées",
"co_name" : "Nom de la société",
"addr" : "Adresse",
"x_coor" : "Axe des x",
"y_coor" : "Axe des y",
"zoom" : "Zoom",
"msg_19" : "Optimal: 16 ~ 17",
"msg_20" : "Afficher la carte des rues",
"terrain" : "Terrain",
"satellite" : "Satellite",
"msg_21" : "Voir les images satellites",
"msg_22" : "Afficher en plein écran",
"find" : "Rechercher",
"zoom_in" : "Agrandir",
"zoom_out" : "Dézoomer",
"table_setting" : "Modifier le tableau",
"design" : "Création",
"head_color" : "Couleur de la tête",
"caption" : "Légende",
"msg_23" : "La légende de la table doit être saisie.",
"summary" : "Résumé",
"msg_24" : "Ex) Table composée de 3 colonnes, 1ère colonne: Taille du Real Eastate, 2ème colonne: Prix de vente par taille, 3ème colonne: Prix de location par taille",
"table_btn_1" : "Fusionner les cellules",
"table_btn_2" : "Division verticale de cellule",
"table_btn_3" : "Division horizontale de cellule",
"table_btn_4" : "Largeur de la cellule égale",
"table_btn_5" : "Changer de gauche et de droite",
"table_btn_6" : "Modifier la commande supérieure et inférieure",
"table_btn_7" : "Ajouter une colonne à droite",
"table_btn_8" : "Ajouter une colonne à gauche",
"table_btn_9" : "Ajouter une colonne en bas",
"table_btn_10" : "Ajouter une colonne en haut",
"table_btn_11" : "Supprimer la ligne",
"table_btn_12" : "Supprimer la cellule",
"table_btn_13" : "Supprimer la table",
"content" : "Contenu",
"msg_26" : "Ne pas appliquer sur l'étiquette principale (P)",
"object_setting" : "Paramètres d'objet",
"general_setting" : "Réglages généraux",
"class" : "Classe",
"style" : "Style",
"shape" : "Forme",
"pattern" : "modèle",
"color" : "Couleur",
"effect" : "Effet",
"text" : "Texte",
"custom" : "Personnalisé",
"line_height" : "Hauteur de ligne",
"word_spacing" : "Décalage du tracé",
"letter_spacing" : "Espacement des lettres",
"border" : "Bordure",
"width" : "Largeur",
"all" : "Tout",
"solid" : "Continue",
"dotted" : "Pointillés",
"dashed" : "Tirets",
"double" : "Double",
"groove" : "Groove",
"ridge" : "Crête",
"inset" : "Encart",
"outset" : "Début",
"radius" : "Rayon de bordure",
"text_shadow" : "Ombre de texte",
"top_left" : "Supérieur gauche",
"top_right" : "Supérieur droit",
"bottom_left" : "Inférieur gauche",
"bottom_right" : "Inférieur gauche",
"bg_color" : "Couleur d'arrière-plan",
"bg" : "Arrière-plan",
"property_remove" : "Réinitialiser",
"padding" : "Marge interne",
"location" : "Emplacement",
"margin" : "Marge",
"text_align" : "Alignement du texte",
"none" : "Aucun",
"center" : "Centrer",
"vertical_align" : "Alignement vertical",
"bold" : "Gras",
"italic" : "Italique",
"underline" : "Souligner",
"line_through" : "Ligne en travers",
"font_family" : "Police",
"sup" : "Exposant",
"sub" : "Indice",
"link" : "Lien",
"top" : "Haut",
"right" : "Droite",
"bottom" : "Bas",
"left" : "Gauche",
"center" : "Centrer",
"msg_27" : "Impossible de modifier le type pour l'élément actuel",
"msg_28" : "Fait pour changer [%1]",
"msg_29" : "Télécharger uniquement le fichier image Fichier d'extension disponible [jpg, jpeg, gif, png, bmp]",
"msg_30" : "[%1] est une image déjà téléchargée!",
"msg_31" : "[%1] fichiers peuvent être téléchargés",
"msg_32" : "Impossible de télécharger un fichier de taille supérieure à [% 3].",
"msg_33" : "Impossible de recharger à cause de l'extension de fichier [%1]",
"set_list" : "Liste d'édition",
"msg_34" : "Sélectionnez le champ à copier.",
"msg_35" : "Sélectionnez le champ à supprimer.",
"msg_36" : "Entrez le contenu.",
"msg_37" : "Si vous quittez cette page, le contenu ne sera pas enregistré.",
"msg_38" : "Devrait être sélectionné plus de deux cellules, S'il vous plaît faites glisser et sélectionnez.",
"msg_39" : "Seuls chacun des en-têtes [thead], content [tbody], footer [tfoot] peuvent être fusionnés",
"msg_40" : "Plage de traînée invalide. Faites glisser dans une forme carrée.",
"msg_41" : "Impossible de changer en raison de <thead>",
"msg_42" : "Disponible seulement une ligne",
"msg_43" : "Incapable de se poursuivre en raison de <tfoot>",
"msg_44" : "Sélectionnez plus d'une cellule pour la division verticale",
"msg_45" : "Sélectionnez plus d'une cellule pour la division horizontale",
"msg_46" : "Impossible de copier la balise [%1]",
"msg_47" : "Possibilité de grouper la copie sur Sélectionnez [OK] pour la copie de groupe Sélectionnez [NON] pour une copie individuelle.",
"msg_48" : "Mauvais emplacement pour l'insert extérieur.",
"msg_49" : "Exemple de paragraphe, facile à modifier en utilisant Editor et Text Converter.",
"msg_50" : "Possibilité de supprimer [Groupe] pour Sélectionner [OK] pour la suppression de groupe Sélectionnez [NON] pour la suppression individuelle.",
"msg_51" : "Impossible de supprimer plus",
"msg_52" : "Éléments de séquence impossibles (balise) à réorganiser",
"msg_53" : "Vous pouvez changer la commande en [Groupe]. Si vous souhaitez modifier l'ordre [groupe], veuillez sélectionner OK. Si vous sélectionnez NON, seul l’objet actuellement sélectionné changera l’ordre.",
"remove_font_property" : "Supprimer la propriété de police",
"delete_link" : "Supprimer le lien",
"top_copy" : "Top Copie",
"msg_54" : "Drags textes principaux pour souhaiter insérer.",
"msg_55" : "Impossible de dépasser le nombre total de cellules [%1]",
"msg_56" : "Impossible de supprimer plus",
"msg_57" : "Impossible de s'étendre plus",
"msg_58" : "Impossible de réduire plus",
"msg_59" : "Description d'entrée de l'image",
"msg_60" : "Adresse d'entrée à lier.",
"msg_61" : "Si coché, le lien s'ouvrira dans une nouvelle fenêtre.",
"msg_62" : "Impossible de réduire plus",
"print_place" : "Emplacement d'impression",
"print_address" : "Adresse d'impression",
"msg_63" : "Déplacez le marqueur pour définir la position correcte.",
"merge" : "Fusionner",
"divide" : "Diviser",
"convert" : "Convertir",
"fix" : "Réparer",
"add" : "Ajouter",
"remove" : "Retirer",
"spacing" : "Espacement",
"text_color" : "Couleur du texte",
"font_size" : "Taille de police",
"font_class" : "Classe de police",
"msg_64" : "Sélectionnez l'emplacement à copier.",
"msg_65" : "Sélectionnez l'emplacement à insérer.",
"msg_66" : "Impossible de supprimer la balise [%1]",
"strong" : "Accentuation",
"save" : "Enregistrer",
"new_content" : "Nouveau",
"msg_67" : "Supprimer ce document?",
"msg_68" : "Voulez-vous supprimer? Impossible de restaurer.",
"msg_69" : "Impossible de copier avec la fonction de verrouillage.",
"inherit" : "Hériter",
"msg_70" : "Non disponible en mode PC!",
"msg_71" : "Traitement",
"column_set" : "Alignement colonne", 
"msg_72" : "Mobile uniquement",
"complete" : "Totale", 

"set_tab" : "Boîte à onglets Paramètres",
"slide" : "Diapositive",

"set_program" : "Paramètres du programme Ajax",
"id" : "ID",
"program_name" : "Nom du programme",
"program_type" : "Type de programme",
"db" : "Base de données",

"tag_setting" : "Paramètres du marquage",
"tag" : "Balise",
"property" : "Propriété",

"HEADING" : "HEADING",
"P" : "P",
"DIV" : "DIV",
"A" : "LINK",
"SPAN" : "SPAN",
"BLOCKQUOTE" : "BLOCKQUOTE",

"msg_73" : "Copié",
"group" : "Groupe",
"no" : "Nombre",
"mouseover" : "Pointeur sur",
"preview" : "Aperçu",
"view" : "Affichage",
"hide" : "Masquer",
"msg_74" : "Saisissez le texte à afficher.",
    
// 2023-05-04 추가
"button_setting" : "Paramètres du bouton",
"use" : "Utiliser",
"msg_75" : "Impossible de coller l'objet.",
"msg_76" : "Aucun objet copié.",
"mode" : "Mode",
"msg_77" : "Uniquement possible dans la balise [tbody] !",
"msg_78" : "Impossible de superposer [%1].",
"map_setting" : "Paramètres de la carte",
"msg_79" : "Veuillez saisir l'adresse à rechercher.", 
"msg_80" : "Cette fonction est disponible uniquement dans la version PRO. \nMettez à niveau pour utiliser plus de fonctionnalités.",
"msg_81" : "Mettre à niveau maintenant",
"grid_setting" : "Paramètres de la grill",
"msg_82" : "Uniquement possible sur PC.",
};