var Msg = {
"fix_html" : "Editar HTML",
"msg_1" : "Capaz de modificar o código HTML.",
"msg_2" : "Impossível Restaurar",
"set_order" : "Mudar o pedido",
"msg_3" : "Mover pelo botão Pressionar",
"widen" : "Ampliar",
"narrow" : "Limitar",
"set_type" : "Alterar Tipo",
"msg_4" : "Definir nenhum tipo de largura",
"add_column" : "Adicionar Nova Coluna",
"msg_5" : "Adicione um espaço em branco",
"add_grid" : "Adicionar uma grade",
"msg_6" : "Adicione uma linha",
"alignment" : "Alinhamento",
"justify" : "Justificar",
"indent" : "Avançar",
"outdent" : "Diminuir Avanço",
"setting" : "Definição",
"title" : "Heading(H)",
"paragraph" : "Paragraph(P)",
"box" : "Division(DIV)",
"text" : "Span",
"blockquote" : "Blockquote",
"fix_size" : "Alterar o Tamanho",
"exsertion" : "Inserção Externa",
"insertion" : "Inserção Interna",
"image" : "Imagem",
"unorder_list" : "Lista não ordenada",
"order_list" : "Lista ordenada",
"table" : "Tabela",
"special_characters" : "Caracteres especiais",
"icon" : "Ícone",
"button" : "botão",
"video" : "vídeo",
"map" : "mapa",
"copy" : "cópia",
"paste" : "colar",
"msg_25" : "clique",
"delete" : "Eliminar",
"upload" : "Carregar",
"msg_7" : "Tamanho ideal",
"msg_8" : "Clique duas vezes para aplicar depois de definir o tamanho.",
"set_link" : "Alterar link",
"explan" : "Explicação",
"msg_9" : "Insira o destino do link",
"url" : "URL",
"msg_10" : "Actualizar endereço do site (URL)",
"new_window" : "Nova janela",
"msg_11" : "Abra em uma nova janela.",
"msg_12" : "Definir o modo básico",
"msg_13" : "Definir o modo de fundo",
"basic_mode" : "Modo Basico",
"background_mode" : "Modo Bacground",
"set_location" : "alterar a localização",
"optimal" : "Optimizado",
"size_up" : "Tamanho até",
"size_down" : "Tamanho para baixo",
"apply" : "aplicar",
"msg_14" : "Não é possível reduzir o tamanho",
"search" : "Pesquisa",
"etc" : "Etc",
"or" : "Ou",
"set_icon" : "Definir ícone",
"msg_15" : "Clique duas vezes para alterar o ícone.",
"size" : "Tamanho",
"auto" : "Automático",
"kind" : "tipo",
"classifiction" : "Classificação",
"set_color" : "Mudar cor",
"symbols" : "Símbolos Gerais",
"numbers_units" : "Números e unidades",
"bracket" : "Parêntese Reto",
"circle" : "Círculo",
"korean" : "coreano",
"greek_latin" : "Grego, latim",
"japanese" : "japonês",
"set_shape" : "Definir forma",
"set_button" : "Botão de configuração",
"msg_16" : "Você pode fazer mais variedade com [Configurações].",
"insert" : "Inserir",
"delete" : "Eliminar",
"msg_17" : "O ícone não existe.",
"set_style" : "Definir Estilo",
"msg_18" : "Não é possível definir devido a organizar em linha única",
"set_video" : "Definir vídeo",
"enter_url" : "Insira o URL (endereço do link, caminho do arquivo)",
"enter_code" : "Digite o código fonte",
"fix_map" : "Mudar Mapa",
"set_map" : "Editar mapa",
"find_coor" : "Encontrar coordenadas",
"co_name" : "Nome da Empresa",
"addr" : "Endereço",
"x_coor" : "Coordenada X",
"y_coor" : "Coordenada Y",
"zoom" : "Zoom",
"msg_19" : "Ideal: 16 ~ 17",
"msg_20" : "Mostrar mapa de ruas",
"terrain" : "Terreno",
"satellite" : "Satélite",
"msg_21" : "Ver imagens de satélite",
"msg_22" : "Visualizar tela inteira",
"find" : "find",
"zoom_in" : "Mais Zoom",
"zoom_out" : "Reduzir o zoom",
"table_setting" : "Editar tabela",
"design" : "Estrutura",
"head_color" : "Cor da cabeça",
"caption" : "Legenda",
"msg_23" : "A legenda da tabela deve ser inserida.",
"summary" : "Resumo",
"msg_24" : "Ex) Tabela composta por 3 colunas, 1ª coluna: Tamanho do Real Eastate, 2ª coluna: Preço de Vendas por Tamanho, 3ª Coluna: Preço de Aluguel por Tamanho",
"table_btn_1" : "Unir células",
"table_btn_2" : "Divisão Vertical Celular",
"table_btn_3" : "Divisão Horizontal Celular",
"table_btn_4" : "Largura da Célula Igual",
"table_btn_5" : "Alterar a ordem esquerda e direita",
"table_btn_6" : "Alterar ordem superior e inferior",
"table_btn_7" : "Adicionar coluna à direita",
"table_btn_8" : "Adicionar coluna à esquerda",
"table_btn_9" : "Adicionar Coluna no Fundo",
"table_btn_10" : "Adicionar Coluna na Parte Superior",
"table_btn_11" : "Eliminar Linha",
"table_btn_12" : "Excluir celular",
"table_btn_13" : "Eliminar Tabela",
"content" : "conteúdo",
"msg_26" : "Não se aplica na tag principal (P)",
"object_setting" : "Configurações de objeto",
"general_setting" : "Configurações Gerais",
"class" : "Classe",
"style" : "Estilo",
"shape" : "Forma",
"pattern" : "padrão",
"color" : "cor",
"effect" : "Efeito",
"text" : "texto",
"custom" : "Personalizado",
"line_height" : "Altura da linha",
"word_spacing" : "Espaço Entre Palavras de Tinta Digital",
"letter_spacing" : "Espaçamento entre letras",
"border" : "Borda",
"width" : "Espessura",
"all" : "Tudo",
"solid" : "sólido",
"dotted" : "Pontilhado",
"dashed" : "Tracejado",
"double" : "Duplo",
"groove" : "Groove",
"ridge" : "Cume",
"inset" : "Inserir",
"outset" : "Início",
"radius" : "Raio da borda",
"text_shadow" : "Sombra de texto",
"top_left" : "Superior à esquerda",
"top_right" : "Superior à direita",
"bottom_left" : "Inferior à esquerda",
"bottom_right" : "Inferior à direita",
"bg_color" : "Cor de fundo",
"bg" : "Fundo",
"property_remove" : "Repor",
"padding" : "Espaçamento",
"location" : "Localização",
"margin" : "Margem",
"text_align" : "Alinhamento do texto",
"none" : "Nenhum",
"center" : "Centro",
"vertical_align" : "Alinhamento vertical",
"bold" : "Negrito",
"italic" : "Itálico",
"underline" : "Sublinhar",
"line_through" : "Rasurado",
"font_family" : "Fonte",
"sup" : "Sobrescrito",
"sub" : "Subscrito",
"link" : "Ligação",
"top" : "Superior",
"right" : "Direita",
"bottom" : "Inferior",
"left" : "Esquerda",
"center" : "Centro",
"msg_27" : "Não é possível alterar o tipo do item atual",
"msg_28" : "Feito para mudar [%1]",
"msg_29" : "Apenas upload de arquivo de imagem Arquivo de extensão disponível [jpg, jpeg, gif, png, bmp]",
"msg_30" : "[%1] é aleady carregou a imagem!",
"msg_31" : "[%1] arquivos podem ser enviados",
"msg_32" : "Não é possível fazer upload de arquivos com tamanho excedendo [% 3].",
"msg_33" : "Não é possível atualizar devido à extensão do arquivo [%1]",
"set_list" : "Lista de edição",
"msg_34" : "Selecione o campo para copiar.",
"msg_35" : "Selecione o campo para excluir.",
"msg_36" : "Digite o conteúdo.",
"msg_37" : "Se você sair desta página, o conteúdo não será salvo.",
"msg_38" : "Deve ser selecionado mais de duas células, por favor, arraste e selecione.",
"msg_39" : "Apenas cada cabeçalho [thead], conteúdo [tbody], footer [tfoot] pode ser mesclado",
"msg_40" : "Intervalo de arrastar inválido. Arraste em uma forma quadrada.",
"msg_41" : "Não é possível alterar devido a <thead>",
"msg_42" : "Disponível apenas uma linha",
"msg_43" : "Incapaz de chace devido a <tfoot>",
"msg_44" : "Selecione mais de uma célula para a divisão vertical",
"msg_45" : "Selecione mais de uma célula para a divisão horizontal",
"msg_46" : "Não é possível copiar para a tag [%1]",
"msg_47" : "Capaz de Agrupar Copiar para Seleccionar [OK] para Cópia de Grupo Seleccione [NÃO] para cópia individual.",
"msg_48" : "Localização incorreta para inserção exteranl.",
"msg_49" : "Exemplo de Parágrafo, Fácil de modificar usando Editor e Conversor de Texto.",
"msg_50" : "Apagar Apagar [Grupo] para Selecionar [OK] para Grupo Apagar Selecione [NÃO] para Apagar Individual.",
"msg_51" : "Não é possível excluir mais",
"msg_52" : "Elementos de sequência não compatíveis (tag) para reordenar",
"msg_53" : "Você pode alterar a ordem para [Group]. Se você quiser alterar o pedido [group], selecione OK. Se você selecionar NÃO, somente o [Objeto] atualmente selecionado mudará a ordem",
"remove_font_property" : "Remover propriedade da fonte",
"delete_link" : "Excluir link",
"top_copy" : "Cópia superior",
"msg_54" : "Arrasta os textos principais para desejar inserir.",
"msg_55" : "Não é possível exceder o total de [%1] células",
"msg_56" : "Não é possível excluir mais",
"msg_57" : "Não é possível estender mais",
"msg_58" : "Não é possível reduzir mais",
"msg_59" : "Entrada Descrição da imagem",
"msg_60" : "Endereço de entrada para link.",
"msg_61" : "Se marcado, o link será aberto em uma nova janela.",
"msg_62" : "Não é possível reduzir mais",
"print_place" : "Localização de impressão",
"print_address" : "Endereço de impressão",
"msg_63" : "Mova o marcador para definir a posição correta.",
"merge" : "Mesclar",
"divide" : "Dividir",
"convert" : "Converter",
"fix" : "Consertar",
"add" : "Adicionar",
"remove" : "Remover",
"spacing" : "Espaçamento",
"text_color" : "Cor do texto",
"font_size" : "Tamanho da fonte",
"font_class" : "Classe de fonte",
"msg_64" : "Selecione o local para copiar.",
"msg_65" : "Selecione o local para inserir.",
"msg_66" : "Não é possível excluir a tag [%1].",
"strong" : "Ênfase",
"save" : "Guardar",
"new_content" : "Novo",
"msg_67" : "Excluir este documento?",
"msg_68" : "Você quer deletar? Não é possível restaurar.",
"msg_69" : "Não é possível copiar com a função de bloqueio.",
"inherit" : "Herdar",
"msg_70" : "Não disponível no modo PC.",
"msg_71" : "Continuar",
"column_set" : "Alinhamento da coluna", 
"msg_72" : "Apenas móvel",
"complete" : "Completo", 

"set_tab" : "Configurações da caixa de guia",
"slide" : "Diapositivo",

"set_program" : "Configurações do Programa Ajax",
"id" : "ID",
"program_name" : "Nome do programa",
"program_type" : "Tipo de Programa",
"db" : "Base de Dados",

"tag_setting" : "Definições de identificação",
"tag" : "Etiqueta",
"property" : "Propriedade",

"HEADING" : "HEADING",
"P" : "P",
"DIV" : "DIV",
"A" : "LINK",
"SPAN" : "SPAN",
"BLOCKQUOTE" : "BLOCKQUOTE",

"msg_73" : "Copiada",
"group" : "Grupo",
"no" : "Número",
"mouseover" : "Rato Sobre",
"preview" : "Pré-visualizar",
"view" : "Ver",
"hide" : "Ocultar",
"msg_74" : "Digite o texto a ser exibido.",
    
// 2023-05-04 추가
"button_setting" : "Configuração do botão",
"use" : "Usar",
"msg_75" : "Não é possível colar o objeto.",
"msg_76" : "Nenhum objeto copiado.",
"mode" : "Modo",
"msg_77" : "Somente possível em tags [tbody]!",
"msg_78" : "Não é possível aninhar [%1]!",
"map_setting" : "Configuração do mapa",
"msg_79" : "Por favor, insira o endereço a ser pesquisado", 
"msg_80" : "Esta funcionalidade está disponível apenas na versão PRO. Atualize para utilizar mais recursos.",
"msg_81" : "Atualizar agora",
"grid_setting" : "Configuração de grade",
"msg_82" : "Disponível apenas no PC.",
};